services:    
    meniloss_sms_factor.request_manager:
        class: Meniloss\SmsFactorBundle\Model\RequestManager
        arguments:
            -      
            
    meniloss_sms_factor.message_manager:
        class: Meniloss\SmsFactorBundle\Model\MessageManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
        
    meniloss_sms_factor.account_manager:
        class: Meniloss\SmsFactorBundle\Model\AccountManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
    
    meniloss_sms_factor.campaign_manager:
        class: Meniloss\SmsFactorBundle\Model\CampaignManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
        
    meniloss_sms_factor.list_manager:
        class: Meniloss\SmsFactorBundle\Model\ListManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
        
    meniloss_sms_factor.token_manager:
        class: Meniloss\SmsFactorBundle\Model\TokenManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
        
    meniloss_sms_factor.webhook_manager:
        class: Meniloss\SmsFactorBundle\Model\WebhookManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
            
    meniloss.sms_factor:
        class: Meniloss\SmsFactorBundle\Service\SmsFactorService
        arguments:
            - '@meniloss_sms_factor.message_manager'
            - '@meniloss_sms_factor.account_manager'
            - '@meniloss_sms_factor.campaign_manager'
            - '@meniloss_sms_factor.list_manager'
            - '@meniloss_sms_factor.token_manager'
            - '@meniloss_sms_factor.webhook_manager'
