services:            
    meniloss.sms_factor:
        class: Meniloss\PrimoTextoBundle\Service\SmsFactorService
        arguments:
            - '@meniloss_sms_factor.message_manager'
            - '@meniloss_sms_factor.account_manager'
            - '@meniloss_sms_factor.campaign_manager'
            - '@meniloss_sms_factor.list_manager'
            - '@meniloss_sms_factor.token_manager'
            - '@meniloss_sms_factor.webhook_manager'
            
    meniloss_sms_factor.message_manager:
        class: Meniloss\PrimoTextoBundle\Model\MessageManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
        
    meniloss_sms_factor.account_manager:
        class: Meniloss\PrimoTextoBundle\Model\AccountManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
    
    meniloss_sms_factor.campaign_manager:
        class: Meniloss\PrimoTextoBundle\Model\CampaignManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
        
    meniloss_sms_factor.list_manager:
        class: Meniloss\PrimoTextoBundle\Model\ListManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
        
    meniloss_sms_factor.token_manager:
        class: Meniloss\PrimoTextoBundle\Model\TokenManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
        
    meniloss_sms_factor.webhook_manager:
        class: Meniloss\PrimoTextoBundle\Model\WebhooManager
        arguments:
            - '@meniloss_sms_factor.request_manager'
    
    meniloss_sms_factor.request_manager:
        class: Meniloss\PrimoTextoBundle\Model\RequestManager
        arguments:
            - 
            
#    meniloss_primo_texto.example:
#        class: Meniloss\PrimoTextoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
